### ISSUE TITLE
NVIDIA GPU But Run On CPU - 电脑是独显但程序警告CUDA不可用改用CPU

### ISSUE THREAD

**Issue by Xiaoyaosouth** [Sanster/iopaint-docs#49]
My desktop use CPU i5-12400F and GPU NVIDIA RTX3070SUPER. I can play games with my GPU.

I used `pip3 install torch==2.1.2 torchvision==0.16.2` to install the torch successfully, then installed IOPaint. But it warned me "CUDA is not available, use cpu instead". I don't know what's wrong with my operation.

```bash
d:\Download>pip3 install torch==2.1.2 torchvision==0.16.2
Looking in indexes: https://pypi.python.org/simple/
Collecting torch==2.1.2
  Downloading torch-2.1.2-cp39-cp39-win_amd64.whl.metadata (26 kB)
Collecting torchvision==0.16.2
  Downloading torchvision-0.16.2-cp39-cp39-win_amd64.whl.metadata (6.6 kB)
Collecting filelock (from torch==2.1.2)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions (from torch==2.1.2)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.1.2)
  Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.1.2)
  Downloading networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting jinja2 (from torch==2.1.2)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.1.2)
  Downloading fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting numpy (from torchvision==0.16.2)
  Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl.metadata (59 kB)
Collecting requests (from torchvision==0.16.2)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.16.2)
  Downloading pillow-11.0.0-cp39-cp39-win_amd64.whl.metadata (9.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.1.2)
  Downloading MarkupSafe-3.0.2-cp39-cp39-win_amd64.whl.metadata (4.1 kB)
Collecting charset-normalizer<4,>=2 (from requests->torchvision==0.16.2)
  Downloading charset_normalizer-3.4.0-cp39-cp39-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->torchvision==0.16.2)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->torchvision==0.16.2)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->torchvision==0.16.2)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.1.2)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading torch-2.1.2-cp39-cp39-win_amd64.whl (192.2 MB)
   ---------------------------------------- 192.2/192.2 MB 7.0 MB/s eta 0:00:00
Downloading torchvision-0.16.2-cp39-cp39-win_amd64.whl (1.1 MB)
   ---------------------------------------- 1.1/1.1 MB 719.0 kB/s eta 0:00:00
Downloading pillow-11.0.0-cp39-cp39-win_amd64.whl (2.6 MB)
   ---------------------------------------- 2.6/2.6 MB 7.8 MB/s eta 0:00:00
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Downloading fsspec-2024.10.0-py3-none-any.whl (179 kB)
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 1.6/1.6 MB 7.4 MB/s eta 0:00:00
Downloading numpy-2.0.2-cp39-cp39-win_amd64.whl (15.9 MB)
   ---------------------------------------- 15.9/15.9 MB 8.8 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading sympy-1.13.3-py3-none-any.whl (6.2 MB)
   ---------------------------------------- 6.2/6.2 MB 9.7 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-3.4.0-cp39-cp39-win_amd64.whl (102 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading MarkupSafe-3.0.2-cp39-cp39-win_amd64.whl (15 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 536.2/536.2 kB 8.8 MB/s eta 0:00:00
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-3.0.2 certifi-2024.8.30 charset-normalizer-3.4.0 filelock-3.16.1 fsspec-2024.10.0 idna-3.10 jinja2-3.1.4 mpmath-1.3.0 networkx-3.2.1 numpy-2.0.2 pillow-11.0.0 requests-2.32.3 sympy-1.13.3 torch-2.1.2 torchvision-0.16.2 typing-extensions-4.12.2 urllib3-2.2.3
```

Then Run IOPaint

```bash
d:\Download>python --version
Python 3.9.13

d:\Download>pip --version
pip 24.3.1 from D:\dev-env\Python3913\lib\site-packages\pip (python 3.9)

d:\Download>iopaint start --model=lama --device=cuda --port=8088
2024-12-11 11:18:32.499 | INFO     | iopaint.runtime:setup_model_dir:80 - Model directory: C:\Users\xiaoyao\.cache
2024-12-11 11:18:32.500 | INFO     | iopaint.runtime:setup_model_dir:84 - Create model directory: C:\Users\xiaoyao\.cache
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.9.13
- torch: 2.1.2
- torchvision: 0.16.2
- Pillow: 9.5.0
- diffusers: 0.27.2
- transformers: 4.47.0
- opencv-python: 4.10.0.84
- accelerate: 1.2.0
- iopaint: 1.5.4
- rembg: N/A

2024-12-11 11:18:34.060 | WARNING  | iopaint.runtime:check_device:67 - CUDA is not available, use cpu instead
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
2024-12-11 11:18:35.395 | INFO     | iopaint.cli:start:183 - lama not found in C:\Users\xiaoyao\.cache, try to downloading
2024-12-11 11:18:35.395 | INFO     | iopaint.download:cli_download_model:27 - Downloading lama...
Downloading: "https://github.com/Sanster/models/releases/download/add_big_lama/big-lama.pt" to C:\Users\xiaoyao\.cache\torch\hub\checkpoints\big-lama.pt
100%|███████████████████████████████████████████████████████████████████████████████| 196M/196M [00:26<00:00, 7.73MB/s]
2024-12-11 11:19:04.274 | INFO     | iopaint.helper:download_model:57 - Download model success, md5: e3aa4aaa15225a33ec84f9f4bc47e500
2024-12-11 11:19:04.274 | INFO     | iopaint.download:cli_download_model:29 - Done.
{
    "host": "127.0.0.1",
    "port": 8088,
    "inbrowser": false,
    "model": "lama",
    "no_half": false,
    "low_mem": false,
    "cpu_offload": false,
    "disable_nsfw_checker": false,
    "local_files_only": false,
    "cpu_textencoder": false,
    "device": "cpu",
    "input": null,
    "mask_dir": null,
    "output_dir": null,
    "quality": 95,
    "enable_interactive_seg": false,
    "interactive_seg_model": "sam2_1_tiny",
    "interactive_seg_device": "cpu",
    "enable_remove_bg": false,
    "remove_bg_device": "cpu",
    "remove_bg_model": "briaai/RMBG-1.4",
    "enable_anime_seg": false,
    "enable_realesrgan": false,
    "realesrgan_device": "cpu",
    "realesrgan_model": "realesr-general-x4v3",
    "enable_gfpgan": false,
    "gfpgan_device": "cpu",
    "enable_restoreformer": false,
    "restoreformer_device": "cpu"
}
2024-12-11 11:19:04.342 | INFO     | iopaint.model_manager:init_model:46 - Loading model: lama
2024-12-11 11:19:04.343 | INFO     | iopaint.helper:load_jit_model:107 - Loading model from: C:\Users\xiaoyao\.cache\torch\hub\checkpoints\big-lama.pt
INFO:     Started server process [14588]
```

**Comment by Sanster** [comment]
```bash
pip3 install torch==2.1.2 torchvision==0.16.2
```

默认是安装 cpu 版本，可查看 pytorch 官网安装符合你 cuda 版本的 gpu 版本：https://pytorch.org/get-started/locally/

<img width="639" alt="image" src="https://github.com/user-attachments/assets/79f541cc-5bf6-4900-87e3-96d74c99c9ed">

**Comment by Xiaoyaosouth** [comment]
> ```shell
> pip3 install torch==2.1.2 torchvision==0.16.2
> ```
> 
> 默认是安装 cpu 版本，可查看 pytorch 官网安装符合你 cuda 版本的 gpu 版本：https://pytorch.org/get-started/locally/
> 
> <img alt="image" width="639" src="https://private-user-images.githubusercontent.com/3998421/394588708-79f541cc-5bf6-4900-87e3-96d74c99c9ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzQwNTAsIm5iZiI6MTczMzk3Mzc1MCwicGF0aCI6Ii8zOTk4NDIxLzM5NDU4ODcwOC03OWY1NDFjYy01YmY2LTQ5MDAtODdlMy05NmQ3NGM5OWM5ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMDMyMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI2MzFjMzg5MWZlNzVjNzJhMTJmYzkyYjYyNzFhYThlYzg3MzFhNWEzZGFmZjgwNGQ2ZjFmYTY2NTMwMTJiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qWdyc1aSxhS9UxrB_-24HR6ERHnp0SPW9x61TmiE0CA">

感谢作者回复，明白了，安装gpu版本的torch必须用 [https://pytorch.org/get-started/locally/](url) 提供的指令。

**Comment by Xiaoyaosouth** [comment]
已解决该问题，下面是我的处理流程。

在cmd用`nvidia-smi` 查看独显驱动和cuda版本。
接着`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124`
因为太慢我选择了手动下载whl包，然后
`pip install "torch-2.5.1+cu124-cp39-cp39-win_amd64.whl" --index-url https://download.pytorch.org/whl/cu124`

```bash
D:\Download>pip install "torch-2.5.1+cu124-cp39-cp39-win_amd64.whl" --index-url https://download.pytorch.org/whl/cu124
Looking in indexes: https://download.pytorch.org/whl/cu124
Processing d:\download\torch-2.5.1+cu124-cp39-cp39-win_amd64.whl
Requirement already satisfied: filelock in d:\dev-env\python3913\lib\site-packages (from torch==2.5.1+cu124) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\dev-env\python3913\lib\site-packages (from torch==2.5.1+cu124) (4.12.2)
Requirement already satisfied: networkx in d:\dev-env\python3913\lib\site-packages (from torch==2.5.1+cu124) (3.2.1)
Requirement already satisfied: jinja2 in d:\dev-env\python3913\lib\site-packages (from torch==2.5.1+cu124) (3.1.4)
Requirement already satisfied: fsspec in d:\dev-env\python3913\lib\site-packages (from torch==2.5.1+cu124) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in d:\dev-env\python3913\lib\site-packages (from torch==2.5.1+cu124) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\dev-env\python3913\lib\site-packages (from sympy==1.13.1->torch==2.5.1+cu124) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\dev-env\python3913\lib\site-packages (from jinja2->torch==2.5.1+cu124) (2.1.5)
Installing collected packages: torch
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.2 requires torch==2.1.2, but you have torch 2.5.1+cu124 which is incompatible.
torchvision 0.16.2 requires torch==2.1.2, but you have torch 2.5.1+cu124 which is incompatible.
Successfully installed torch-2.5.1+cu124
```

更新torchaudio和torchvision
`pip install --upgrade torchaudio`
`pip install --upgrade torchvision`

检查torch和cuda支持状态
```bash
D:\Download>python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.5.1+cu124
>>> print(torch.version.cuda)
12.4
>>> print(torch.cuda.is_available())
True
```

启动iopaint
```bash
D:\Download>iopaint start --model=lama --device=cuda --port=8088
2024-12-12 10:59:19.422 | INFO     | iopaint.runtime:setup_model_dir:80 - Model directory: C:\Users\xiaoyao\.cache
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.9.13
- torch: 2.5.1+cu124
- torchvision: 0.20.1
- Pillow: 9.5.0
- diffusers: 0.27.2
- transformers: 4.47.0
- opencv-python: 4.10.0.84
- accelerate: 1.2.0
- iopaint: 1.5.4
- rembg: N/A

D:\dev-env\Python3913\lib\site-packages\iopaint\model\ldm.py:279: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @torch.cuda.amp.autocast()
[W1212 10:59:24.000000000 init.cpp:768] Warning: nvfuser is no longer supported in torch script, use _jit_set_nvfuser_enabled is deprecated and a no-op (function operator ())
{
    "host": "127.0.0.1",
    "port": 8088,
    "inbrowser": false,
    "model": "lama",
    "no_half": false,
    "low_mem": false,
    "cpu_offload": false,
    "disable_nsfw_checker": false,
    "local_files_only": false,
    "cpu_textencoder": false,
    "device": "cuda",
    "input": null,
    "mask_dir": null,
    "output_dir": null,
    "quality": 95,
    "enable_interactive_seg": false,
    "interactive_seg_model": "sam2_1_tiny",
    "interactive_seg_device": "cpu",
    "enable_remove_bg": false,
    "remove_bg_device": "cpu",
    "remove_bg_model": "briaai/RMBG-1.4",
    "enable_anime_seg": false,
    "enable_realesrgan": false,
    "realesrgan_device": "cpu",
    "realesrgan_model": "realesr-general-x4v3",
    "enable_gfpgan": false,
    "gfpgan_device": "cpu",
    "enable_restoreformer": false,
    "restoreformer_device": "cpu"
}
2024-12-12 10:59:24.069 | INFO     | iopaint.model_manager:init_model:46 - Loading model: lama
2024-12-12 10:59:24.070 | INFO     | iopaint.helper:load_jit_model:107 - Loading model from: C:\Users\xiaoyao\.cache\torch\hub\checkpoints\big-lama.pt
INFO:     Started server process [12852]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8088 (Press CTRL+C to quit)
```
